### ISSUE TITLE
Method Blocking

### ISSUE THREAD

**Issue by STR0M0** [N8STROMO/Basic-Chat-Server-Client#1]
The ReceiveData() method within client.cs is blocking the progression of the app. Need to look at refactoring this project asynchronously.

**Comment by theogjpeezy** [comment]
I took a look at this today and was able to make this process run on another thread.  I have noticed that there are more issues beyond this though.  I am unsure at this time if you are looking for contributions to get this working end to end, or if you are simply looking for someone to remove a roadblock so that you can go on with the project.  
If you just need someone to remove the roadblock I can make a pull request and you can take a look.  If it is the later, I can dig further.

**Comment by STR0M0** [comment]
Thank you for interest in my project! I would appreciate it if you did send a pull request so that I can take a look at your code. I am doing this to learn mostly so I don't exactly want it handed to me, but I will be sure to reach out to you if I have additional questions or run into another road block. Kindest Regards JP
